<hr style="border:5px solid #108999"> </hr>

# Sales Data <hr style="border:4.5px solid #108999"> </hr>

In [2]:
import pandas as pd
import datetime
import pytz
from matplotlib import pyplot as plt
data = pd.read_csv('Sales-products-tz-exam-set.csv', index_col = 'SaleID')
sales_products = data.copy()
sales_products

,RetailerCountry,RetailerType,Product,DateOfSale,TimeOfSale,Timezone
SaleID,,,,,,
SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,06/01/2020,23:20:56,EST
SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,05/02/2020,17:27:08,EST
SaleID_3,United States,Outdoors Shop,Star Dome,30/10/2020,09:04:43,EST
SaleID_4,United States,Outdoors Shop,Star Gazer 2,13/11/2020,04:25:06,EST
SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,06/12/2020,11:15:47,CET
...,...,...,...,...,...,...
SaleID_96,Austria,Sports Store,Mountain Man Extreme,23/07/2019,12:30:03,CET
SaleID_97,Australia,Department Store,Firefly Mapreader,03/01/2019,01:39:14,Australia/ACT
SaleID_98,Australia,Discount Retailer,Polar Sun,14/02/2019,21:29:35,Australia/ACT
SaleID_99,Australia,Discount Retailer,Polar Ice,19/06/2020,11:16:19,Australia/ACT
SaleID_100,Australia,Discount Retailer,Polar Sports,25/05/2019,15:51:41,Australia/ACT

In [3]:
# Show a summary of the dataframe
sales_products.describe()

,RetailerCountry,RetailerType,Product,DateOfSale,TimeOfSale,Timezone
count,100,100,99,100,100,100
unique,11,7,71,94,100,7
top,Canada,Outdoors Shop,Polar Sun,06/12/2020,23:20:56,CET
freq,32,37,4,2,1,40

In [19]:
# Time difference between the first and second Outdoors Shop sale
first_product = pd.to_datetime(sales_products['DateOfSale'].iloc[0], format='%d/%m/%Y')
#print(first_product)
second_product = pd.to_datetime(sales_products['DateOfSale'].iloc[1], format='%d/%m/%Y')
#print(second_product)
delta = (first_product - second_product)
print("Days inbetween:", abs(delta.days))

Days inbetween: 30

In [7]:
# create Unit timestamp value in another column by combining DateOfSale and TimeOfSale
sales_products['DateTimeStamp'] = pd.to_datetime(sales_products['DateOfSale'] +" "+ sales_products['TimeOfSale'], dayfirst=True)
sales_products

,RetailerCountry,RetailerType,Product,DateOfSale,TimeOfSale,Timezone,DateTimeStamp
SaleID,,,,,,,
SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,06/01/2020,23:20:56,EST,2020-01-06 23:20:56
SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,05/02/2020,17:27:08,EST,2020-02-05 17:27:08
SaleID_3,United States,Outdoors Shop,Star Dome,30/10/2020,09:04:43,EST,2020-10-30 09:04:43
SaleID_4,United States,Outdoors Shop,Star Gazer 2,13/11/2020,04:25:06,EST,2020-11-13 04:25:06
SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,06/12/2020,11:15:47,CET,2020-12-06 11:15:47
...,...,...,...,...,...,...,...
SaleID_96,Austria,Sports Store,Mountain Man Extreme,23/07/2019,12:30:03,CET,2019-07-23 12:30:03
SaleID_97,Australia,Department Store,Firefly Mapreader,03/01/2019,01:39:14,Australia/ACT,2019-01-03 01:39:14
SaleID_98,Australia,Discount Retailer,Polar Sun,14/02/2019,21:29:35,Australia/ACT,2019-02-14 21:29:35
SaleID_99,Australia,Discount Retailer,Polar Ice,19/06/2020,11:16:19,Australia/ACT,2020-06-19 11:16:19
SaleID_100,Australia,Discount Retailer,Polar Sports,25/05/2019,15:51:41,Australia/ACT,2019-05-25 15:51:41

In [8]:
# Reorder the columns with DateTimeStamp after TimeOfSale
column_names_reordered = ['RetailerCountry', 'RetailerType', 'Product', 'DateOfSale', 'TimeOfSale', 'DateTimeStamp', 'Timezone']
sales_products = sales_products[column_names_reordered]
sales_products.head()

,RetailerCountry,RetailerType,Product,DateOfSale,TimeOfSale,DateTimeStamp,Timezone
SaleID,,,,,,,
SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,06/01/2020,23:20:56,2020-01-06 23:20:56,EST
SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,05/02/2020,17:27:08,2020-02-05 17:27:08,EST
SaleID_3,United States,Outdoors Shop,Star Dome,30/10/2020,09:04:43,2020-10-30 09:04:43,EST
SaleID_4,United States,Outdoors Shop,Star Gazer 2,13/11/2020,04:25:06,2020-11-13 04:25:06,EST
SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,06/12/2020,11:15:47,2020-12-06 11:15:47,CET

In [15]:
# convert each date-time to a Unix timestamp
from datetime import datetime
# 'apply' applies the lambda function to each value in the DateTimeStamp column to convert it into a Unix timestamp
sales_products['UnixTimeStamp'] = pd.to_datetime(sales_products['DateTimeStamp']).apply(lambda x: x.timestamp())
sales_products

,RetailerCountry,RetailerType,Product,DateOfSale,TimeOfSale,DateTimeStamp,Timezone,UNIX,UnixTimeStamp
SaleID,,,,,,,,,
SaleID_1,United States,Outdoors Shop,TrailChef Deluxe Cook Set,06/01/2020,23:20:56,2020-01-06 23:20:56,EST,1.578353e+09,1.578353e+09
SaleID_2,United States,Outdoors Shop,TrailChef Double Flame,05/02/2020,17:27:08,2020-02-05 17:27:08,EST,1.580924e+09,1.580924e+09
SaleID_3,United States,Outdoors Shop,Star Dome,30/10/2020,09:04:43,2020-10-30 09:04:43,EST,1.604049e+09,1.604049e+09
SaleID_4,United States,Outdoors Shop,Star Gazer 2,13/11/2020,04:25:06,2020-11-13 04:25:06,EST,1.605242e+09,1.605242e+09
SaleID_5,Italy,Outdoors Shop,Canyon Mule Carryall,06/12/2020,11:15:47,2020-12-06 11:15:47,CET,1.607253e+09,1.607253e+09
...,...,...,...,...,...,...,...,...,...
SaleID_96,Austria,Sports Store,Mountain Man Extreme,23/07/2019,12:30:03,2019-07-23 12:30:03,CET,1.563885e+09,1.563885e+09
SaleID_97,Australia,Department Store,Firefly Mapreader,03/01/2019,01:39:14,2019-01-03 01:39:14,Australia/ACT,1.546480e+09,1.546480e+09
SaleID_98,Australia,Discount Retailer,Polar Sun,14/02/2019,21:29:35,2019-02-14 21:29:35,Australia/ACT,1.550180e+09,1.550180e+09
SaleID_99,Australia,Discount Retailer,Polar Ice,19/06/2020,11:16:19,2020-06-19 11:16:19,Australia/ACT,1.592565e+09,1.592565e+09
SaleID_100,Australia,Discount Retailer,Polar Sports,25/05/2019,15:51:41,2019-05-25 15:51:41,Australia/ACT,1.558800e+09,1.558800e+09

Q5